#!/usr/bin/python

# -*- coding: utf-8 -*-

# Copyright (C) 2014 Sylvain Boily <sboily@proformatique.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from xivo import agi
import sugarcrm

debug = 0
agi = agi.AGI()

if debug:
    agi.DEBUG_PASSTHROUGH = 1
    caller = "8000"
    url = "http://crm/service/v4_1/rest.php"
    username = "admin"
    password = "admin"
else:
    caller = agi.env["agi_callerid"]
    url = agi.get_variable("SUGARCRM_URL")
    username = agi.get_variable("SUGARCRM_USERNAME")
    password = agi.get_variable("SUGARCRM_PASSWD")

try:
    if debug:
        print "Trying to connect %s with %s : %s " %(url, username, password)
        print "Searching information for caller %s" % caller
    else:
        agi.verbose("Trying to connect %s with %s : %s " %(url, username, password))
    conn = sugarcrm.Sugarcrm(url, username, password)
except ValueError:
    agi.verbose("can't connect to " + url)
    exit(1)

# Exist :  phone_home phone_mobile phone_work phone_other phone_fax

query = conn.modules['Contacts'].query().filter(phone_work__exact="%s" % caller)
for contact in query:
    if debug:
        print "CONTACT : " + contact['first_name'] + " " + contact['last_name']
        print "SUGARCRM-ID", contact['id']
        print "SUGARCRM-FIRSTNAME", contact['first_name']
        print "SUGARCRM-LASTNAME", contact['last_name']
    else:
        agi.verbose("CONTACT : " + contact['first_name'] + " " + contact['last_name'])
        agi.set_variable("SUGARCRM-ID", contact['id'])
        agi.set_variable("SUGARCRM-FIRSTNAME", contact['first_name'])
        agi.set_variable("SUGARCRM-LASTNAME", contact['last_name'])
